[tool.poetry]
name = "hyperfocus"
version = "0.1.0"
description = ""
authors = ["u8slvn <u8slvn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
peewee = "^3.14.8"
tabulate = "^0.8.9"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-mock = "^3.7.0"
pytest-coverage = "^0.0"
flake8 = "^4.0.1"
black = "^22.1.0"
mypy = "^0.931"
freezegun = "^1.1.0"
isort = "^5.10.1"
types-tabulate = "^0.8.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_third_party = ["peewee"]

[[tool.mypy.overrides]]
module="peewee"
warn_unused_ignores = false
ignore_missing_imports = true
